# Generated by Django 4.1.1 on 2022-10-31 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.TimeField(auto_created=True)),
                ('created_on', models.DateField(auto_created=True)),
                ('sub_acct', models.IntegerField(default=0)),
                ('descr', models.TextField()),
                ('debit', models.DecimalField(decimal_places=2, max_digits=65)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=65)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=65)),
                ('acct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.account')),
            ],
        ),
    ]
